# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b6a33345cd66d9abc8a0757a06672f7538c78ec0d666bd16d324ecfb6aee8ffa1079c9f020d5570d28c5ef49833a1b6c0f87249063f6ece93049aa243c23c15

test:
  secret_key_base: bf2961c4d041a04ed73135e8f64e772ec1ebe4094f6b54b99b7c85db3b10ccbcb92a928156e0c3e08a606a997065d57bcf886c5add94520569f006dc6a4fd5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
